[tool.poetry]
name = "tracking_lib"
version = "0.1.17"
description = ""
authors = ["Damianos Damianidis <cloud.tailwind@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
