# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install pypa/build
        run: python -m pip install build  

      - name: Install pytest
        run: python -m pip install pytest  

      - name: Install fastapi
        run: python -m pip install fastapi 

      - name: Install flask
        run: python -m pip install flask

      - name: Install functions-framework
        run: python -m pip install functions-framework

      - name: Install httpx
        run: python -m pip install httpx   

      - name: Install requests
        run: python -m pip install requests 

      - name: Install google-cloud-pubsub
        run: python -m pip install google-cloud-pubsub              

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
        
      - name: Run tests with pytest
        run: export PYTHONPATH="${PYTHONPATH}:tracking_lib" && pytest 

      - name: Build package
        run: python setup.py sdist bdist_wheel

      - name: Check package
        run: twine check dist/*
      
      - name: upload dists
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  pypi-publish:
    runs-on: ubuntu-latest
    needs:
      - release-build
    permissions:
      id-token: write

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
